package com.macro.mall.model;

import com.macro.mall.enums.InventoryAlertType;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

/**
 * 库存警报实体，用于自动库存预警通知
 * Created for Product Management Module Enhancement
 */
public class InventoryAlert implements Serializable {
    
    private Long id;

    @ApiModelProperty(value = "商品ID")
    @NotNull(message = "商品ID不能为空")
    private Long productId;

    @ApiModelProperty(value = "商品名称")
    private String productName;

    @ApiModelProperty(value = "商品编号")
    private String productSn;

    @ApiModelProperty(value = "仓库ID")
    private Long warehouseId;

    @ApiModelProperty(value = "仓库名称")
    private String warehouseName;

    @ApiModelProperty(value = "警报类型")
    @NotNull(message = "警报类型不能为空")
    private String alertType;

    @ApiModelProperty(value = "警报标题")
    private String alertTitle;

    @ApiModelProperty(value = "警报消息")
    private String alertMessage;

    @ApiModelProperty(value = "警报级别：1->低；2->中；3->高；4->紧急")
    private Integer alertLevel;

    @ApiModelProperty(value = "当前库存数量")
    private Integer currentQuantity;

    @ApiModelProperty(value = "阈值数量")
    private Integer thresholdQuantity;

    @ApiModelProperty(value = "预计缺货天数")
    private Integer estimatedStockoutDays;

    @ApiModelProperty(value = "建议补货数量")
    private Integer suggestedReorderQuantity;

    @ApiModelProperty(value = "供应商ID")
    private Long supplierId;

    @ApiModelProperty(value = "供应商名称")
    private String supplierName;

    @ApiModelProperty(value = "警报状态：0->未处理；1->处理中；2->已处理；3->已忽略")
    private Integer alertStatus;

    @ApiModelProperty(value = "处理人ID")
    private Long handlerId;

    @ApiModelProperty(value = "处理人名称")
    private String handlerName;

    @ApiModelProperty(value = "处理时间")
    private Date handledAt;

    @ApiModelProperty(value = "处理备注")
    private String handlingNotes;

    @ApiModelProperty(value = "处理结果")
    private String handlingResult;

    @ApiModelProperty(value = "是否自动生成")
    private Boolean autoGenerated;

    @ApiModelProperty(value = "是否已发送通知")
    private Boolean notificationSent;

    @ApiModelProperty(value = "通知发送时间")
    private Date notificationSentAt;

    @ApiModelProperty(value = "通知收件人")
    private String notificationRecipients;

    @ApiModelProperty(value = "重复次数")
    private Integer recurrenceCount;

    @ApiModelProperty(value = "下次检查时间")
    private Date nextCheckTime;

    @ApiModelProperty(value = "过期时间")
    private Date expiresAt;

    @ApiModelProperty(value = "是否静音")
    private Boolean isMuted;

    @ApiModelProperty(value = "静音到期时间")
    private Date muteExpiresAt;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "更新时间")
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    // Constructors
    public InventoryAlert() {
        this.createdAt = new Date();
        this.updatedAt = new Date();
        this.alertStatus = 0; // 默认未处理
        this.autoGenerated = true;
        this.notificationSent = false;
        this.isMuted = false;
        this.recurrenceCount = 0;
    }

    public InventoryAlert(Long productId, InventoryAlertType type, Integer currentQuantity, Integer threshold) {
        this();
        this.productId = productId;
        this.alertType = type.getCode();
        this.alertTitle = type.getName();
        this.alertLevel = type.getPriority();
        this.currentQuantity = currentQuantity;
        this.thresholdQuantity = threshold;
        generateAlertMessage();
    }

    // Business methods
    public InventoryAlertType getAlertTypeEnum() {
        return this.alertType != null ? InventoryAlertType.fromCode(this.alertType) : null;
    }

    public void setAlertTypeEnum(InventoryAlertType type) {
        this.alertType = type.getCode();
        this.alertTitle = type.getName();
        this.alertLevel = type.getPriority();
    }

    public boolean isPending() {
        return this.alertStatus == null || this.alertStatus == 0;
    }

    public boolean isProcessing() {
        return this.alertStatus != null && this.alertStatus == 1;
    }

    public boolean isProcessed() {
        return this.alertStatus != null && this.alertStatus == 2;
    }

    public boolean isIgnored() {
        return this.alertStatus != null && this.alertStatus == 3;
    }

    public boolean isExpired() {
        return this.expiresAt != null && this.expiresAt.before(new Date());
    }

    public boolean isMutedNow() {
        if (!this.isMuted) return false;
        if (this.muteExpiresAt == null) return true;
        return this.muteExpiresAt.after(new Date());
    }

    public boolean requiresImmediateAction() {
        InventoryAlertType type = getAlertTypeEnum();
        return type != null && type.requiresImmediateAction();
    }

    public boolean isHighPriority() {
        return this.alertLevel != null && this.alertLevel <= 2;
    }

    public boolean shouldSendNotification() {
        return !this.notificationSent && !isMutedNow() && !isExpired() && isPending();
    }

    public void generateAlertMessage() {
        InventoryAlertType type = getAlertTypeEnum();
        if (type == null) return;

        StringBuilder message = new StringBuilder();
        message.append("商品 ").append(this.productName != null ? this.productName : "ID:" + this.productId);
        
        switch (type) {
            case LOW_STOCK:
                message.append(" 库存不足，当前库存：").append(this.currentQuantity)
                       .append("，补货点：").append(this.thresholdQuantity);
                break;
            case OUT_OF_STOCK:
                message.append(" 已缺货，请立即补货");
                break;
            case OVERSTOCK:
                message.append(" 库存过多，当前库存：").append(this.currentQuantity)
                       .append("，建议减少采购");
                break;
            case EXPIRED_PRODUCTS:
                message.append(" 即将过期或已过期，请及时处理");
                break;
            case REORDER_POINT:
                message.append(" 达到补货点，建议补货数量：").append(this.suggestedReorderQuantity);
                break;
            default:
                message.append(" 需要关注：").append(type.getDescription());
        }

        this.alertMessage = message.toString();
    }

    public void markAsProcessing(Long handlerId, String notes) {
        this.alertStatus = 1;
        this.handlerId = handlerId;
        this.handledAt = new Date();
        this.handlingNotes = notes;
        this.updatedAt = new Date();
    }

    public void markAsProcessed(String result) {
        this.alertStatus = 2;
        this.handlingResult = result;
        this.updatedAt = new Date();
    }

    public void markAsIgnored(String reason) {
        this.alertStatus = 3;
        this.handlingResult = reason;
        this.updatedAt = new Date();
    }

    public void mute(int hours) {
        this.isMuted = true;
        if (hours > 0) {
            this.muteExpiresAt = new Date(System.currentTimeMillis() + hours * 60 * 60 * 1000L);
        }
        this.updatedAt = new Date();
    }

    public void unmute() {
        this.isMuted = false;
        this.muteExpiresAt = null;
        this.updatedAt = new Date();
    }

    public void markNotificationSent(String recipients) {
        this.notificationSent = true;
        this.notificationSentAt = new Date();
        this.notificationRecipients = recipients;
        this.updatedAt = new Date();
    }

    public void incrementRecurrence() {
        this.recurrenceCount = (this.recurrenceCount != null ? this.recurrenceCount : 0) + 1;
        this.updatedAt = new Date();
    }

    public boolean needsEscalation() {
        return this.recurrenceCount != null && this.recurrenceCount >= 3 && isPending();
    }

    public int getDaysOld() {
        if (this.createdAt == null) return 0;
        return (int) ((new Date().getTime() - this.createdAt.getTime()) / (1000 * 60 * 60 * 24));
    }

    public boolean isStale() {
        return getDaysOld() > 7; // 超过7天的警报认为是过期的
    }

    public String getPriorityText() {
        if (this.alertLevel == null) return "未知";
        switch (this.alertLevel) {
            case 1: return "紧急";
            case 2: return "高";
            case 3: return "中";
            case 4: return "低";
            default: return "未知";
        }
    }

    public String getStatusText() {
        if (this.alertStatus == null) return "未处理";
        switch (this.alertStatus) {
            case 0: return "未处理";
            case 1: return "处理中";
            case 2: return "已处理";
            case 3: return "已忽略";
            default: return "未知";
        }
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
        generateAlertMessage(); // 重新生成消息
    }

    public String getProductSn() {
        return productSn;
    }

    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public String getAlertTitle() {
        return alertTitle;
    }

    public void setAlertTitle(String alertTitle) {
        this.alertTitle = alertTitle;
    }

    public String getAlertMessage() {
        return alertMessage;
    }

    public void setAlertMessage(String alertMessage) {
        this.alertMessage = alertMessage;
    }

    public Integer getAlertLevel() {
        return alertLevel;
    }

    public void setAlertLevel(Integer alertLevel) {
        this.alertLevel = alertLevel;
    }

    public Integer getCurrentQuantity() {
        return currentQuantity;
    }

    public void setCurrentQuantity(Integer currentQuantity) {
        this.currentQuantity = currentQuantity;
        generateAlertMessage(); // 重新生成消息
    }

    public Integer getThresholdQuantity() {
        return thresholdQuantity;
    }

    public void setThresholdQuantity(Integer thresholdQuantity) {
        this.thresholdQuantity = thresholdQuantity;
        generateAlertMessage(); // 重新生成消息
    }

    public Integer getAlertStatus() {
        return alertStatus;
    }

    public void setAlertStatus(Integer alertStatus) {
        this.alertStatus = alertStatus;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ... 其他getter/setter方法

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", alertType=").append(alertType);
        sb.append(", alertLevel=").append(alertLevel);
        sb.append(", currentQuantity=").append(currentQuantity);
        sb.append(", thresholdQuantity=").append(thresholdQuantity);
        sb.append(", alertStatus=").append(alertStatus);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}