package com.macro.mall.model;

import com.macro.mall.enums.StockMovementType;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 库存移动记录实体，用于库存变化审计追踪
 * Created for Product Management Module Enhancement
 */
public class StockMovement implements Serializable {
    
    private Long id;

    @ApiModelProperty(value = "商品ID")
    @NotNull(message = "商品ID不能为空")
    private Long productId;

    @ApiModelProperty(value = "商品名称")
    private String productName;

    @ApiModelProperty(value = "商品编号")
    private String productSn;

    @ApiModelProperty(value = "仓库ID")
    private Long warehouseId;

    @ApiModelProperty(value = "仓库名称")
    private String warehouseName;

    @ApiModelProperty(value = "移动类型")
    @NotNull(message = "移动类型不能为空")
    private String movementType;

    @ApiModelProperty(value = "移动数量（正数为入库，负数为出库）")
    @NotNull(message = "移动数量不能为空")
    private Integer quantity;

    @ApiModelProperty(value = "移动前库存数量")
    private Integer quantityBefore;

    @ApiModelProperty(value = "移动后库存数量")
    private Integer quantityAfter;

    @ApiModelProperty(value = "单价")
    private BigDecimal unitPrice;

    @ApiModelProperty(value = "总金额")
    private BigDecimal totalAmount;

    @ApiModelProperty(value = "参考单号（订单号、采购单号等）")
    private String referenceNumber;

    @ApiModelProperty(value = "参考类型（ORDER, PURCHASE, RETURN等）")
    private String referenceType;

    @ApiModelProperty(value = "批次号")
    private String batchNumber;

    @ApiModelProperty(value = "有效期")
    private Date expiryDate;

    @ApiModelProperty(value = "供应商ID")
    private Long supplierId;

    @ApiModelProperty(value = "供应商名称")
    private String supplierName;

    @ApiModelProperty(value = "客户ID")
    private Long customerId;

    @ApiModelProperty(value = "客户名称")
    private String customerName;

    @ApiModelProperty(value = "操作原因")
    private String reason;

    @ApiModelProperty(value = "备注")
    private String notes;

    @ApiModelProperty(value = "操作人ID")
    private Long operatorId;

    @ApiModelProperty(value = "操作人名称")
    private String operatorName;

    @ApiModelProperty(value = "操作时间")
    private Date operationTime;

    @ApiModelProperty(value = "系统自动操作标识")
    private Boolean autoGenerated;

    @ApiModelProperty(value = "关联的库存记录ID")
    private Long inventoryRecordId;

    @ApiModelProperty(value = "源仓库ID（调拨时使用）")
    private Long sourceWarehouseId;

    @ApiModelProperty(value = "目标仓库ID（调拨时使用）")
    private Long targetWarehouseId;

    @ApiModelProperty(value = "成本中心")
    private String costCenter;

    @ApiModelProperty(value = "会计期间")
    private String accountingPeriod;

    @ApiModelProperty(value = "审核状态：0->待审核；1->已审核；2->已拒绝")
    private Integer auditStatus;

    @ApiModelProperty(value = "审核人ID")
    private Long auditorId;

    @ApiModelProperty(value = "审核时间")
    private Date auditTime;

    @ApiModelProperty(value = "审核备注")
    private String auditNotes;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "更新时间")
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    // Constructors
    public StockMovement() {
        this.operationTime = new Date();
        this.createdAt = new Date();
        this.updatedAt = new Date();
        this.autoGenerated = false;
        this.auditStatus = 0; // 默认待审核
    }

    public StockMovement(Long productId, StockMovementType type, Integer quantity, Long operatorId, String reason) {
        this();
        this.productId = productId;
        this.movementType = type.getCode();
        this.quantity = quantity;
        this.operatorId = operatorId;
        this.reason = reason;
    }

    // Business methods
    public StockMovementType getMovementTypeEnum() {
        return this.movementType != null ? StockMovementType.fromCode(this.movementType) : null;
    }

    public void setMovementTypeEnum(StockMovementType type) {
        this.movementType = type.getCode();
    }

    public boolean isInbound() {
        StockMovementType type = getMovementTypeEnum();
        if (type == null) return false;
        
        // 对于调整类型，根据数量判断
        if (type == StockMovementType.ADJUSTMENT) {
            return this.quantity != null && this.quantity > 0;
        }
        
        return type.isInbound();
    }

    public boolean isOutbound() {
        StockMovementType type = getMovementTypeEnum();
        if (type == null) return false;
        
        // 对于调整类型，根据数量判断
        if (type == StockMovementType.ADJUSTMENT) {
            return this.quantity != null && this.quantity < 0;
        }
        
        return type.isOutbound();
    }

    public Integer getAbsoluteQuantity() {
        return this.quantity != null ? Math.abs(this.quantity) : 0;
    }

    public BigDecimal calculateTotalAmount() {
        if (this.unitPrice == null || this.quantity == null) return BigDecimal.ZERO;
        return this.unitPrice.multiply(new BigDecimal(Math.abs(this.quantity)));
    }

    public boolean requiresApproval() {
        StockMovementType type = getMovementTypeEnum();
        if (type == null) return false;
        
        // 高价值或大数量的移动需要审核
        BigDecimal highValueThreshold = new BigDecimal("10000"); // 1万元以上
        Integer highQuantityThreshold = 1000; // 1000件以上
        
        boolean isHighValue = this.totalAmount != null && this.totalAmount.compareTo(highValueThreshold) > 0;
        boolean isHighQuantity = this.quantity != null && Math.abs(this.quantity) > highQuantityThreshold;
        boolean isHighRiskType = type == StockMovementType.DAMAGE || 
                                type == StockMovementType.ADJUSTMENT ||
                                type == StockMovementType.TRANSFER_OUT;
        
        return isHighValue || isHighQuantity || isHighRiskType;
    }

    public boolean isApproved() {
        return this.auditStatus != null && this.auditStatus == 1;
    }

    public boolean isPending() {
        return this.auditStatus == null || this.auditStatus == 0;
    }

    public boolean isRejected() {
        return this.auditStatus != null && this.auditStatus == 2;
    }

    public void approve(Long auditorId, String notes) {
        this.auditStatus = 1;
        this.auditorId = auditorId;
        this.auditTime = new Date();
        this.auditNotes = notes;
        this.updatedAt = new Date();
    }

    public void reject(Long auditorId, String notes) {
        this.auditStatus = 2;
        this.auditorId = auditorId;
        this.auditTime = new Date();
        this.auditNotes = notes;
        this.updatedAt = new Date();
    }

    public String getMovementDirection() {
        if (this.quantity == null) return "UNKNOWN";
        if (this.quantity > 0) return "IN";
        if (this.quantity < 0) return "OUT";
        return "NONE";
    }

    public boolean isTransfer() {
        StockMovementType type = getMovementTypeEnum();
        return type == StockMovementType.TRANSFER_IN || type == StockMovementType.TRANSFER_OUT;
    }

    public boolean isValid() {
        return this.productId != null && 
               this.movementType != null && 
               this.quantity != null && 
               this.quantity != 0 &&
               this.operatorId != null;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductSn() {
        return productSn;
    }

    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    public Long getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    public String getMovementType() {
        return movementType;
    }

    public void setMovementType(String movementType) {
        this.movementType = movementType;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getQuantityBefore() {
        return quantityBefore;
    }

    public void setQuantityBefore(Integer quantityBefore) {
        this.quantityBefore = quantityBefore;
    }

    public Integer getQuantityAfter() {
        return quantityAfter;
    }

    public void setQuantityAfter(Integer quantityAfter) {
        this.quantityAfter = quantityAfter;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
        if (this.quantity != null && unitPrice != null) {
            this.totalAmount = calculateTotalAmount();
        }
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getReferenceNumber() {
        return referenceNumber;
    }

    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Long getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public Date getOperationTime() {
        return operationTime;
    }

    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    // ... 其他getter/setter方法

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", movementType=").append(movementType);
        sb.append(", quantity=").append(quantity);
        sb.append(", quantityBefore=").append(quantityBefore);
        sb.append(", quantityAfter=").append(quantityAfter);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}